services:
  db:
    build:
      context: ./db
    env_file:
      - .env
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: 
      context: ./
    container_name: flask_server
    env_file:
      - .env
    environment:
      FLASK_ENV: development
      DB_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
