version: '3.8'

services:
  db:
    build:
      context: ./db/Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: ./Dockerfile
    container_name: flask_server
    environment:
      FLASK_ENV: development
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend
    command: python ./run_server.py

volumes:
  - postgres_data:

networks:
  backend:

