name: CI

on:
  pull_request:
    branches:
      - develop
      - trunk

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    environment: test

    services:
      docker:
        image: docker:27-cli
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test env
      run: |
        echo ${{ env.DB_USER }}
        echo ${{ env.DB_PASSWORD }}
        if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
          echo "ERROR: DB_USER or DB_PASSWORD is not set."
          exit 1
        fi
      env:
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up docker compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose

    - name: Build containers
      run: |
        echo ${{ env.DB_USER }}
        echo ${{ env.DB_PASSWORD }}
        make install
      env:
        DOCKER_BUILDKIT: 1
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}

    - name: View logs
      run: |
        docker-compose logs db
        docker-compose logs web

    - name: Build and run with Docker Compose
      run: |
        make lint
        make test
      env:
        DOCKER_BUILDKIT: 1
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}

    - name: Stop and remove containers
      run: |
        make clean
