name: CI

on:
  pull_request:
    branches:
      - develop
      - trunk

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run with Docker Compose
      run: |
        make lint
        make test
      env:
        DOCKER_BUILDKIT: 1

    - name: Stop and remove containers
      run: |
        make clean
